import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import Header from "./component/Header";
import Footer from "./component/Footer";
import "../styles/globals.css";
import '../assets/css/styles.css';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="stylesheet" href="/assets/css/styles.css" precedence="default" />
      <body className={inter.className}>
      <section className="top-bg">
       <Header/>
      </section>
        {children}
      <Footer/>
        </body>
    </html>
  );
}
